# pyright: reportGeneralTypeIssues=false, reportOptionalMemberAccess=false
from youtube_transcript_api import YouTubeTranscriptApi
import re

# return of ytt_api.fetch() -> <class 'youtube_transcript_api._transcripts.FetchedTranscript'>
"""
"_rR4szKm9dQ" : 영어
"IFx8eABfivg" : es
"gPlWn17cseQ" : cnn, manually created, no translation
"""
video_id = "_rR4szKm9dQ"
ytt_api = YouTubeTranscriptApi()
transcript_list = ytt_api.list(video_id)

MANUALLY_CREATED_transcript=None
GENERATED_transcript=None

for transcript in transcript_list:
    if transcript.is_generated==False:
        print(f'this {transcript.language} is manually created')
        MANUALLY_CREATED_transcript=transcript
    elif transcript.is_generated==True:
        print(f'this {transcript.language} is generated by YouTube')
        GENERATED_transcript=transcript
if MANUALLY_CREATED_transcript == None:
    print('MANUALLY_CREATED_transcript is None')
elif MANUALLY_CREATED_transcript!=None:
    print(f'MANUALLY_CREATED_transcript is here')
    print(f'language code of manually_created_transcript: {MANUALLY_CREATED_transcript.language_code}')
    print(MANUALLY_CREATED_transcript.fetch())


if GENERATED_transcript==None:
    print('GENERATED_transcript is None')
elif GENERATED_transcript!=None:
    print(f'GENERATED_transcript is here')  
    print(f'language code of GENERATED_transcript: {GENERATED_transcript.language_code}')
#    print(GENERATED_transcript.fetch())
    #print(GENERATED_transcript.fetch([GENERATED_transcript.language_code]))

selected_transcript=GENERATED_transcript.fetch()

merged_output = []
current_text = ""
current_start_time = ""
max_length = 500  # 원하는 최대 길이 설정
for snippet in selected_transcript:
    text = snippet.text
    if not current_text:
        if snippet.start <3600:
            current_start_time = f'[{snippet.start//60:02.0f}:{snippet.start%60:02.0f}]'
        else:
            current_start_time = f'[{snippet.start//3600:02.0f}:{snippet.start%3600//60:02.0f}:{snippet.start%60:02.2f}]'            
        
    current_text += (" " + text) if current_text else text
    
    if (re.search(r'[.?!]$', text) and len(current_text) >= max_length) or \
       (len(current_text) > max_length * 1.2): # 20% 마진을 두어 안전성 확보
        merged_output.append(f"{current_start_time} {current_text.strip()}")
        current_text = ""
        current_start_time = ""
if current_text:
    merged_output.append(f"{current_start_time} {current_text.strip()}")
transcript_be_report = "\n".join(merged_output)

print(transcript_be_report)



"""
print(f'start of transcript')
print(transcript_list)

for transcript in transcript_list:

    # the Transcript object provides metadata properties
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,
        # whether it has been manually created or generated by YouTube
        transcript.is_generated,
        # whether this transcript can be translated or not
        transcript.is_translatable,
        # a list of languages the transcript can be translated to
        transcript.translation_languages,
    )

    # fetch the actual transcript data
    print(transcript.fetch())
    translated_transcript=transcript.translate('ko')

    # translating the transcript will return another transcript object
    print(translated_transcript.fetch())
"""
"""
count=0
transcript_to_translate=None
fetched_transcript=None
for transcript in transcript_list:
    if transcript.is_generated==False:
        print(f'this {transcript.language} is manually created')
    elif transcript.is_generated==True:
        print(f'this {transcript.language} is generated by YouTube')
    transcipt_to_translate=transcript
    
    count+=1
print(f'count: {count}')
fetched_transcript=transcript_to_translate.fetch()
print(f'Before translate: \n{fetched_transcript}')
fetched_transcript=transcript_to_translate.translate("ko")
print(f'After translated to ko: {fetched_transcript}')
"""    
"""
for transcript in transcript_list:
        # the Transcript object provides metadata properties
        print(
            transcript.video_id,
            transcript.language,
            transcript.language_code,
            # whether it has been manually created or generated by YouTube
            transcript.is_generated,
            # a list of languages the transcript can be translated to
            transcript.translation_languages,
        )
        print('\n')
        """

"""
fetched_transcript=ytt_api.fetch(video_id=video_id)
print(f'len(fetched_transcript): {len(fetched_transcript)}')
print(type(fetched_transcript.to_raw_data()))
"""




"""
print(f'type of return of YouTubeTranscriptApi.fetch() is {type(fetched_transcript)}')
print(fetched_transcript)
print(f'len(fetched_transcript): {len(fetched_transcript)}')
"""

"""transcript_list = ytt_api.list(VIDEO_ID)
# is iterable
print(f'type of return of YouTubeTranscriptApi.fetch() is {type(fetched_transcript)}')
print(f'type of return of YouTubeTranscriptApi.list() is {type(transcript_list)}')

for snippet in fetched_transcript:
    print(snippet.text)

print(f'Snippet count: {len(fetched_transcript)}')
# indexable
last_snippet = fetched_transcript[-1]

print(f'fetched_transcript[-1]: {fetched_transcript[-1]}')
print(f'fetched_transcript[-0]: {fetched_transcript[0]}')
print(f'fetched_transcript[207]: {fetched_transcript[207]}')
print{last_snippet}"""
